I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label _call_endStamp_38 is defined twice, at
  File "game/script.rpy", line 6248 and
  File "game/script.rpy", line 6479.

Ren'Py Version: Ren'Py 7.4.4.1439
Thu Sep  1 16:28:22 2022
