I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 310, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 793, in script
    if name4Rand == 1:
  File "game/script.rpy", line 793, in <module>
    if name4Rand == 1:
NameError: name 'name4Rand' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 310, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 793, in script
    if name4Rand == 1:
  File "renpy/ast.py", line 1852, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 793, in <module>
    if name4Rand == 1:
NameError: name 'name4Rand' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
The Thief, the Toad, the Witch & the Mushroom 0.81
Fri Jul 22 16:47:24 2022
