I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 314, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 1227, in script
    $renpy.music.play("audio/rememberDistVocalFull.wav", channel="music", fadein=5.0, volume=0.5, loop=False)
  File "game/script.rpy", line 1227, in <module>
    $renpy.music.play("audio/rememberDistVocalFull.wav", channel="music", fadein=5.0, volume=0.5, loop=False)
TypeError: play() got an unexpected keyword argument 'volume'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 314, in script call
    call expression "before_main_menu"
  File "game/script.rpy", line 1227, in script
    $renpy.music.play("audio/rememberDistVocalFull.wav", channel="music", fadein=5.0, volume=0.5, loop=False)
  File "D:\ThiefWitchToadMushroom\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\ThiefWitchToadMushroom\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 1227, in <module>
    $renpy.music.play("audio/rememberDistVocalFull.wav", channel="music", fadein=5.0, volume=0.5, loop=False)
TypeError: play() got an unexpected keyword argument 'volume'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
The Wolf. 1.0
Fri Mar  8 18:43:41 2024
